name: Example - Generate Atlas

on:
  push:
    branches:
      - public # Triggers on commits to public branch (contains images and assets)
  workflow_dispatch:

# Define permissions needed for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  make-atlas:
    uses: nappollen/udon-poster/.github/workflows/generate-atlas.yml@v1
    with:
      input-path: "images" # Path to your images folder (default: 'images')
    permissions:
      contents: read
      pages: write
      id-token: write
